version : '3.9'

services: 
  app:
    build: 
      context: .
    ports: 
      - 8000:8000
    volumes: 
      - ./app:/app
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=ahr
      - DB_USER=ahroniy
      - DB_PASS=ahroniy
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ahr
      - POSTGRES_USER=ahroniy
      - POSTGRES_PASSWORD=ahroniy
    